name = "rhea-leverage-tracker"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"
pages_build_output_dir = ".vercel/output/static"

[vars]
NODE_VERSION = "18"

# D1 database binding
[[d1_databases]]
binding = "DB"
database_name = "rhea-tracker"
database_id = "c02fa531-b2cb-45cc-947a-dd356e42e091"
